# Form implementation generated from reading ui file 'UI/addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        AddEditCoffeeForm.resize(400, 400)
        self.formWidget = QtWidgets.QWidget(parent=AddEditCoffeeForm)
        self.formWidget.setObjectName("formWidget")
        self.nameEdit = QtWidgets.QLineEdit(parent=self.formWidget)
        self.nameEdit.setGeometry(QtCore.QRect(150, 20, 200, 30))
        self.nameEdit.setObjectName("nameEdit")
        self.roastEdit = QtWidgets.QLineEdit(parent=self.formWidget)
        self.roastEdit.setGeometry(QtCore.QRect(150, 70, 200, 30))
        self.roastEdit.setObjectName("roastEdit")
        self.typeEdit = QtWidgets.QLineEdit(parent=self.formWidget)
        self.typeEdit.setGeometry(QtCore.QRect(150, 120, 200, 30))
        self.typeEdit.setObjectName("typeEdit")
        self.tasteEdit = QtWidgets.QLineEdit(parent=self.formWidget)
        self.tasteEdit.setGeometry(QtCore.QRect(150, 170, 200, 30))
        self.tasteEdit.setObjectName("tasteEdit")
        self.priceEdit = QtWidgets.QLineEdit(parent=self.formWidget)
        self.priceEdit.setGeometry(QtCore.QRect(150, 220, 200, 30))
        self.priceEdit.setObjectName("priceEdit")
        self.volumeEdit = QtWidgets.QLineEdit(parent=self.formWidget)
        self.volumeEdit.setGeometry(QtCore.QRect(150, 270, 200, 30))
        self.volumeEdit.setObjectName("volumeEdit")
        self.saveButton = QtWidgets.QPushButton(parent=self.formWidget)
        self.saveButton.setGeometry(QtCore.QRect(150, 330, 100, 30))
        self.saveButton.setObjectName("saveButton")

        self.retranslateUi(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        AddEditCoffeeForm.setWindowTitle(_translate("AddEditCoffeeForm", "Добавить/Редактировать кофе"))
        self.nameEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Название сорта"))
        self.roastEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Степень обжарки"))
        self.typeEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Тип (Молотый/Зерна)"))
        self.tasteEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Описание вкуса"))
        self.priceEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Цена"))
        self.volumeEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Объем (г)"))
        self.saveButton.setText(_translate("AddEditCoffeeForm", "Сохранить"))
